version: '3'

services:
  geth:
    image: ethereum/client-go:v1.10.13
    tty: true
    volumes:
      - ./scripts:/scripts
    ports:
      - 8222:8222
    environment:
      - GETH_ARGS=--networkid=99 --maxpeers=0 --nodiscover --miner.noverify --miner.gaslimit=24000000 --miner.gasprice=1 --http --http.port=8222 --http.api=eth,net,web3,debug,personal,miner --allow-insecure-unlock --http.addr=0.0.0.0 --http.corsdomain=* --http.vhosts=*
    entrypoint: '/bin/sh -c "geth $$GETH_ARGS init /scripts/genesis.json && geth $$GETH_ARGS --preload /scripts/chainInit.js console"'

  dev:
    depends_on:
      - geth
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    image: node:lts-alpine
    working_dir: /app
    entrypoint: /bin/sh
    command: "-c 'yarn'"
    tty: true
    stdin_open: true
    environment:
      - ROOT_RPC_URL=http://geth:8222/

volumes:
  node_modules:
