name: Coverage

on:
  push:
    branches:
    - master
    - release/*

  pull_request_review_comment:
    types: [created, edited]

  pull_request:
    branches:
    - master

  workflow_dispatch:

jobs:
  messenger:
    if: github.event.comment.body == '/COVERAGE'
    runs-on: ubuntu-latest
    steps:
    - name: messenger
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const commentBody = `https://github.com/${context.payload.repository.full_name}/actions/runs/${context.runId}`
          // Get the existing comments.
          const {data: comments} = await github.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          // Find any comment already made by the bot.
          const botComment = comments.find(comment => comment.user.id === 41898282)
          if (botComment) {
            await github.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: commentBody
            })
          } else {
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            })
          }

  coverage:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event_name == 'pull_request' || github.event.comment.body == '/COVERAGE'
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: docker-compose up --timeout 1 --exit-code-from dev

    - name: Coverage
      run: docker-compose run dev -c 'yarn coverage'

    - name: Upload Coverage
      if: success()
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage-report.lcov
